export default {
  name: 'profile',
  title: 'Sobre Mí / Biografía',
  type: 'document',
  groups: [
    { name: 'hero', title: 'PÁGINA DE INICIO' },
    { name: 'bio', title: 'SOBRE MÍ / BIO' },
    { name: 'visuals', title: 'FOTOS Y VIDEOS' },
    { name: 'contact', title: 'ACCIONES' },
  ],
  fields: [
    {
      name: 'name',
      title: 'Nombre de la Marca (Logo)',
      type: 'string',
      group: 'hero',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'headline',
      title: 'Titular / Breve Descripción',
      type: 'string',
      group: 'hero',
      description: 'Ej: Filmmaker & Montador Audiovisual',
    },
    {
      name: 'heroImage',
      title: 'Imagen de Fondo Portada (Hero)',
      type: 'image',
      group: 'hero',
      options: { hotspot: true },
      description: 'Esta imagen aparecerá de fondo en el inicio de la web.',
    },
    {
      name: 'heroButtons',
      title: 'Botones de Portada (Acciones)',
      type: 'object',
      group: 'contact',
      fields: [
        { name: 'primaryText', title: 'Texto Botón Proyectos', type: 'string', initialValue: 'Ver Proyectos' },
        { name: 'primaryUrl', title: 'Enlace Botón Proyectos', type: 'string', initialValue: '/portfolio' },
        { name: 'secondaryText', title: 'Texto Botón Secundario', type: 'string', initialValue: 'Trabajemos Juntos' },
        { name: 'secondaryUrl', title: 'Enlace Botón Secundario', type: 'string', initialValue: '#contacto' },
      ],
    },
    {
      name: 'bio',
      title: 'Trayectoria / Evolución',
      type: 'text',
      group: 'bio',
      rows: 10,
    },
    {
      name: 'profileImage',
      title: 'Foto de Perfil Principal',
      type: 'image',
      group: 'visuals',
      options: { hotspot: true },
    },
    {
      name: 'actionPhotos',
      title: 'Fotos en Acción (Rodajes, etc.)',
      type: 'array',
      group: 'visuals',
      of: [{ type: 'image' }],
    },
  ],
};
